### PR TITLE
Fix GH-98

### LINKED ISSUE #98: Linking to ID on section which is not chunked does not generate a proper link
Linking to an ID that is on an element with `annotations="chunk:false"` does not work.

Related to https://github.com/php/doc-en/issues/3178

### PR DESCRIPTION
**Pull request by haszi**
Store IDs of non-chunked elements.
Closes #98.

### CODE REVIEW

**Review by Girgias — APPROVED** [review]
LGTM and thank you!

**Comment by Girgias** [comment]
Well the tests seem to fail :thinking:

**Comment by haszi** [comment]
> Well the tests seem to fail 🤔

Yeah, for some reason it doesn't index anything on GH but works perfectly fine locally. I'm trying to figure out what's going on but don't really have a clue what it could be yet.

**Comment by haszi** [comment]
It turns out that `'index' => true` in `Config` doesn't do anything (changed it to `'force_index' => true`) and the `$indexes` property of `Format` is actually the list of indexes read from cache/sqlite and `Index`'s `$nfo` property holds the parsed indexes.

Anyway, the test passes now and this is ready for review.

**Comment by haszi** [comment]
I've changed the private `$nfo` property to `protected` so I can access it from `TestIndex` but now I'm thinking that adding a `getNfo()` method to `Index` may be a better solution.

**Pull request merged**
