### PR TITLE
Fix element map so changelog rows are handled correctly

### PR DESCRIPTION
**Pull request by jimwins**
https://www.php.net/manual/en/doc.changelog.php is empty because this was backwards and changelog entries weren't actually being indexed.

### CODE REVIEW

**Comment by cmb69** [comment]
Hmm, wouldn't that revert bacc87c11a1b209b1a51c201824533558d66ac22? @sy-records can you check?

**Comment by jimwins** [comment]
Yeah, I'm really not quite sure what is going here. Without my change, `format_row()` never gets called so nothing is added to the `$this->changelog` array. But with the change, some things in rows don't get properly linked.

Looks like we have one map that is trying to handle `<tbody><row><entry>` and another just `<tbody><row>` and things are getting confused. `format_entry()` is treating `$this->currentChangelog` as an array of strings, `format_row()` treats it as an array containing of the membership and id?

**Review by sy-records — APPROVED** [review]
I tested it. 

LGTM.

**Comment by jimwins** [comment]
Pushed a change to the PR to do that version splitting. Together with the cleanup in php/doc-en#3672, this results in a `doc.changelog.html` that is 329K, but that includes changes since 5.0.0. Changing it to 8.0.0 takes it down to 274K. (This is configured in `doc-base/manual.xml/in`.)

**Comment by cmb69** [comment]
> […], but that includes changes since 5.0.0.

Actually, the current documentation shouldn't care about PHP 5 anymore.

**Comment by jimwins** [comment]
Opened php/doc-base#146 to bump up it up to 7.0.0. That shaves off ~8K.

**Comment by haszi** [comment]
Could you also add a test showing how the changelog entries are now indexed and another one that shows that whatever was not properly linked after the first commit is now being linked correctly?

**Review by haszi — APPROVED** [review]

**Comment by jimwins** [comment]
Will merge this once php/doc-en#3672 is approved and merged, I'd rather not merge this and end up with the messy changelog that results without those cleanups.

**Pull request merged**
